### ISSUE TITLE
lets build project website design

### ISSUE THREAD

**Issue by kkatusic** [muqa-org/demo#14]
@MaxSemenchuk here we can write proposal features for website design for Muqa.

Some components that I suggest:

- Header: Logo + Menu, maybe add social links, for twitter, github...
- Intro image/text/hero section: add some image with title and short text what is Muqa project. Add link to About us page to read more about project.
- Short boxes info: 3 or for boxes, what is our goal, what impact you can made, how to use our project, how to engage, ...
- Grants/Rounds: maybe to put some info in one row, or multiple rows what is grant, what is rounds, how QF founig works, what is formula, how that formula apply, what is benefit, what make it more democratic... Put some diagram to it how it works...
- Partners: list our partners, our donations, something like that
- Projects/Grants: maybe put some grants that is over or current, this can be add in future
- Blockchain technology: write one row about it, link to more
- Footer

lets begin, thx

**Comment by b0rza** [comment]
@kkatusic @tomislavmamic  I think it is very important to have a good, clear, concise explanation of what the project does. I find myself struggling to get the point across when talking to regular people. We want them to use it, and I think that is going to be very important.
