### ISSUE TITLE
This 2 element should be equal size on heights and rounding radius

### ISSUE THREAD

**Issue by MaxSemenchuk** [muqa-org/demo#75]
Now
<img width="367" alt="image" src="https://github.com/user-attachments/assets/c0c3eb83-b7f1-40fe-acb0-e207b7e26320">

Should be
<img width="262" alt="image" src="https://github.com/user-attachments/assets/d3a75e45-dffd-4bdc-890e-47b7018151be">

**Comment by Nikhiludupa** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
