### ISSUE TITLE
Merging pins in map view

### ISSUE THREAD

**Issue by MaxSemenchuk** [muqa-org/demo#77]
<img width="334" alt="image" src="https://github.com/user-attachments/assets/ab358966-c705-442a-956c-f96dd61228d8">

i haven't designed it, so need to consult with you – when too close to each other ideally i'd expect the pins to be merged into 1 with a number of projects alike this

<img width="259" alt="image" src="https://github.com/user-attachments/assets/9e39091f-3f23-4f1a-bb39-3a598517b9ce">

And when you zoom they transform into separate pins. It's not critical and before we do it just want to check how easy is it for you. If hard we can keep as is, if easy – i can provide a design

**Comment by kkatusic** [comment]
@MaxSemenchuk, let's do some talk here, I need ask main engineer @b0rza . 

@b0rza to provide this feature of the grouping markers on smaller zoom, in terminology it is calling marker clustering, I need to provide new package: https://www.npmjs.com/package/@googlemaps/markerclusterer . And my question is can I add new package and try to solve issue? thx

**Comment by b0rza** [comment]
@kkatusic sure, go ahead!
