### ISSUE TITLE
Form completed screen

### ISSUE THREAD

**Issue by tomislavmamic** [muqa-org/demo#80]
![CleanShot 2024-09-04 at 14 59 11@2x](https://github.com/user-attachments/assets/db19ec94-9378-4d6c-a384-8273559e65ef)

Can we improve this view:

- [ ] Add "Create new proposal" button
- [x] Add link to the post on forum
- [x] Redirect user to the forum post in 5 seconds. Show a message and a timer for this.
- [ ] Stick the footer to the bottom

**Comment by kkatusic** [comment]
@tomislavmamic what you mean when you wrote: "Add "Create new proposal" button" ?

As we added project proposal to locked category, this two tasks: "Add link to the post on forum" and "Redirect user to the forum post in 5 seconds. Show a message and a timer for this." have been solved.
