### ISSUE TITLE
Redirect to proposal topic after submission

### ISSUE THREAD

**Issue by tomislavmamic** [muqa-org/demo#91]
When a user fills out the form, we automatically create the proposal topic in the Forum under "Za provjeru" (For review) category. I've made it so that "Za provjeru" category on Forum is visible to everyone, but only Staff can comment.

Now we can redirect the user to the actual topic immediately after submission. They can see it but not comment. If they click Reply, they will be asked to register. When they register, they won't see the reply button anymore.

- [x] Let's redirect the user to the topic when she submits
- [x] Let's inform user, before redirecting, that they will be redirected to forum topic of the proposal and that they can't comment it:

`Vaš prijedlog je uspješno predan i sada ćete biti preusmjereni na temu prijedloga na našem Forumu. Trenutno ne možete komentirati prijedlog jer se nalazi u fazi provjere od strane našeg stručnog tima. Obavijestit ćemo vas kada javna rasprava bude otvorena. Savjetujemo da se odmah registrirate na forumu.`

- [x] Let's append each new proposals topic with explanation on why user can't comment the proposal yet

`Ovaj prijedlog trenutno prolazi kroz proces provjere. U ovoj fazi, samo članovi našeg stručnog tima mogu komentirati prijedloge. Kada prijedlog bude provjeren i zadovolji sve kriterije, bit će objavljen javno na Forumu i otvoren za komentare. Registrirajte se i zapratite ovu temu da budete informirani o daljnjim koracima.`

**Comment by kkatusic** [comment]
@tomislavmamic please provide me also english translation

**Comment by tomislavmamic** [comment]
“Your proposal has been successfully submitted and you will now be redirected to the proposal topic on our Forum. You currently cannot comment on the proposal as it is under review by our expert team. We will notify you when the public discussion is open.”

“This proposal is currently under review. At this stage, only members of our expert team can comment on proposals. Once the proposal has been reviewed and meets all the criteria, it will be published publicly on the Forum and opened for comments. Please register and follow this topic to stay informed about the next steps.”

**Comment by kkatusic** [comment]
@tomislavmamic 15 seconds to read before redirect is ok to you?

**Comment by MaxSemenchuk** [comment]
Any design needed? 
From the improvements – maybe also send some email notifications on the successful application and link to the forum

**Comment by kkatusic** [comment]
@MaxSemenchuk if you need email notification just confirm and I will add it, @tomislavmamic should provide email message content ;)

**Comment by tomislavmamic** [comment]
## Hrvatski:

**Predmet:** Vaš prijedlog je uspješno zaprimljen!

Poštovani/a [Ime predlagatelja],

Zahvaljujemo što ste podnijeli prijedlog za Zazelenimo Split. Vaš prijedlog je uspješno zaprimljen i trenutno se nalazi u fazi provjere od strane našeg stručnog tima.

Možete vidjeti svoj prijedlog i pratiti njegov napredak na sljedećoj poveznici: [Link na prijedlog]

Imajte na umu da u ovoj fazi nećete moći komentirati prijedlog. Nakon što prijedlog bude provjeren i zadovolji sve uvjete, bit će objavljen javno i otvoren za javnu raspravu. Preporučujemo da se registrirate na naš Forum i zapratite temu kako biste dobivali obavijesti o daljnjim koracima.

Ako imate bilo kakvih pitanja, slobodno nas kontaktirajte.

Srdačan pozdrav,
Zazelenimo Split tim

## English:

**Subject:** Your proposal has been successfully received!

Dear [Proposer’s Name],

Thank you for submitting your proposal for Zazelenimo Split. Your proposal has been successfully received and is currently under review by our expert team.

You can view your proposal and track its progress at the following link: [Link to proposal]

Please note that you will not be able to comment on the proposal at this stage. Once the proposal has been reviewed and meets all the conditions, it will be made public and opened for discussion. We recommend that you register on our Forum and follow the topic to receive notifications on the next steps.

If you have any questions, feel free to contact us.

Best regards,
The Zazelenimo Split Team
