### ISSUE TITLE
Muqa website

### ISSUE THREAD

**Issue by tomislavmamic** [muqa-org/demo#92]
- [x] Outline: https://muqa.notion.site/Muqa-website-d83488cda739423fb4f2fd246df3fe72?pvs=4
- [x] Design: https://www.figma.com/design/3eZqiVcD4bjHBzy8MdabwC/MUQA?node-id=417-819&node-type=frame&t=eGiBKlhierwPBOTp-0
- [x] Content
- [ ] Develop

**Comment by kkatusic** [comment]
@MaxSemenchuk can we start with this notion file, we don't need to write so many text and can make changes every time we want :)

**Comment by tomislavmamic** [comment]
@kkatusic you can start working on the landing page. Everything is done except Statements. You can create this section and hide it for now, and once we have the content, I will send it to you so we can publish that too.

@MaxSemenchuk is now working on About page.

**Comment by kkatusic** [comment]
@MaxSemenchuk and @tomislavmamic please all issue related to website comment on this repository:

https://github.com/muqa-org/website

thx ;)
